# ~/.config/kitty/kitty.conf

# Font
font_family Noto Sans Mono
font_size 13.0

# Moonlit Night
background #070b14
foreground #dce3f2

selection_background #2f3d5f
selection_foreground #ffffff

cursor #9ecbff
cursor_text_color #070b14

# ANSI colors
color0  #0b0f18
color1  #c94f5c
color2  #8fcf8f
color3  #e0a85c
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #dce3f2

color8  #4f5b70
color9  #ff6b7a
color10 #a6e3a1
color11 #f2c879
color12 #9ecbff
color13 #c8a9ff
color14 #9be7ff
color15 #ffffff

# Window chrome
window_padding_width 8
background_opacity 1.0
